module.exports = {
    SOCKET_EVENT_BLACKLIST: [
        "pitching_substitution",
        "batter_timeout",
        "mound_visit",
        "offensive_substitution",
        "defensive_switch",
        "runner_placed",
        "foul",
        "ball",
        "called_strike",
        "swinging_strike",
        "swinging_strike_blocked",
        "hit_into_play",
        "hit_into_play_no_out",
        "foul_tip",
        "at_bat_start",
        "blocked_ball",
        "defensive_indiff",
        "pitcher_step_off",
        "no_pitch",
        "ejection",
        "injury",
        "umpire_substitution"
    ],
    TEAM_ID: 114,
    GUARDIANS: 114, // guardians team ID for MLB stats API
    AMERICAN_LEAGUE: 103,
    AL_CENTRAL: 202,
    STATUS_POLLING_INTERVAL: 30000,
    SLOW_POLL_INTERVAL: 300000,
    HIGHLIGHTS_PER_MESSAGE: 8,
    DATE: null,
    ADMIN_ROLES: [ "Mod" ],
    EVENTS: [
        "Double",
        "Double Play",
        "Field Error",
        "Fielders Choice Out",
        "Flyout",
        "Forceout",
        "Grounded Into DP",
        "Groundout",
        "Hit By Pitch",
        "Home Run",
        "Intent Walk",
        "Lineout",
        "Pop Out",
        "Single",
        "Strikeout",
        "Triple",
        "Walk"
    ]
}
