module.exports = {
    EVENT_WHITELIST:[
        'pickoff_error_1b',
        'pickoff_error_2b',
        'pickoff_error_3b',
        'single',
        'double',
        'triple',
        'field_error',
        'error',
        'catcher_interf',
        'batter_interference',
        'fielder_interference',
        'runner_interference',
        'fan_interference',
        'ejection',
        'defensive_indiff',
        'walk',
        'intent_walk',
        'hit_by_pitch',
        'injury',
        'passed_ball',
        'other_advance',
        'pitching_substitution',
        'offensive_substitution',
        'defensive_switch',
        'pitcher_switch',
        'stolen_base',
        'stolen_base_2b',
        'stolen_base_3b',
        'stolen_base_home',
        'defensive_substitution',
        'balk',
        'forced_balk',
        'wild_pitch'
    ],
    TEAM_ID: 114,
    GUARDIANS: 114, // guardians team ID for MLB stats API
    AL_CENTRAL: 202,
    AMERICAN_LEAGUE: 103,
    DIVISION_ID: 202,
    STATUS_POLLING_INTERVAL: 30000,
    SAVANT_POLLING_INTERVAL: 10000,
    SLOW_POLL_INTERVAL: 300000,
    HIGHLIGHTS_PER_MESSAGE: 8,
    DATE: null,
    ADMIN_ROLES: [ "Mod" ],
    EVENTS: [
        "Double",
        "Double Play",
        "Field Error",
        "Fielders Choice Out",
        "Flyout",
        "Forceout",
        "Grounded Into DP",
        "Groundout",
        "Hit By Pitch",
        "Home Run",
        "Intent Walk",
        "Lineout",
        "Pop Out",
        "Single",
        "Strikeout",
        "Triple",
        "Walk"
    ]
}
